language: python
dist: trusty
sudo: false
branches:
  except:
    - /^v[0-9\.]*/
    - /^untagged.*/
matrix:
  include:
  - python: "2.7"
    env:
    - FLAG=false
      TOXENV=py27
  - python: "3.5"
    env:
    - FLAG=false
      TOXENV=py35
  - python: "3.6"
    env:
    - FLAG=true
      TOXENV=py36
addons:
  apt:
    packages:
    - gcc
    - make
    - libssl-dev
    - python-pip
    - python-dev
    - build-essential
services:
- docker
install:
- travis_retry pip install tox
script:
- make test
- |
  if [[ "$FLAG" == "true" ]]; then
    make build
  fi
deploy:
- provider: script
  skip_cleanup: true
  script: >-
    pip install -U bumpversion &&
    git config --global user.email "builds@travis-ci.com" &&
    git config --global user.name "Travis CI" &&
    git pull -t &&
    git checkout -b travis-master-$TRAVIS_BUILD_NUMBER origin/$TRAVIS_BRANCH &&
    bumpversion --tag --commit --message "[skip ci] Travis Build ${TRAVIS_BUILD_NUMBER}. Update version {current_version} --> {new_version}" patch modeldb/__init__.py
  on:
    branch: master
    condition: $FLAG = true
- provider: script
  skip_cleanup: true
  script: >-
    make clean build upload &&
    git checkout master &&
    git merge travis-master-$TRAVIS_BUILD_NUMBER &&
    git push --tags https://$GITHUB_TOKEN@github.com/engapa/modeldb-basic.git $TRAVIS_BRANCH
  on:
    branch: master
    condition: $FLAG = true
- provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    branch: master
    condition: $FLAG = true

notifications:
  email:
    recipients:
    - engapa@gmail.com
    on_success: never # default: change
    on_failure: always # default: always