language: bash
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - gcc
    - make
    - libssl-dev
    - python-pip
    - python-dev
services:
- docker
install:
- sudo apt-get update
- sudo apt-get -y upgrade
- sudo apt-get install python3.6 python3-pip idle3
- sudo pip install tox
script:
- make test
