language: bash
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - gcc
    - make
    - libssl-dev
    - python-pip
    - python-dev
    - build-essential
    - checkinstall
    - libreadline-gplv2-dev
    - libncursesw5-dev
    - libsqlite3-dev
    - tk-dev
    - libgdbm-dev
    - libc6-dev
    - libbz2-dev
services:
- docker
install:
- cd /usr/src
- sudo wget https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tgz
- sudo tar xzf Python-3.6.2.tgz && cd Python-3.6.2 && sudo ./configure && sudo make altinstall
- sudo pip install tox
script:
- make test
