language: bash
dist: precise
sudo: required
addons:
  apt:
    packages:
    - gcc
    - make
    - libssl-dev
    - python-pip
    - python-dev
services:
- docker
install:
- sudo apt-get update
- sudo add-apt-repository ppa:jonathonf/python-3.6
- sudo apt-get update
- sudo apt-get install -y python3.6
- sudo pip install tox
script:
- make test
