language: bash
dist: trusty
sudo: True
addons:
  apt:
    packages:
    - gcc
    - make
    - libssl-dev
    - python-pip
    - python-dev
python: '3.6'
services:
- docker
install:
- sudo pip install tox
script:
- make test
