language: python
dist: trusty
sudo: false
python:
  - 2.7
  - 3.6
addons:
  apt:
    packages:
    - gcc
    - make
    - libssl-dev
    - python-pip
    - python-dev
    - build-essential
services:
- docker
install:
- travis_retry pip install tox tox-travis
script:
- make test
