language: python
dist: trusty
sudo: false
matrix:
  include:
  - python: "2.7"
    env:
    - FLAG=false
      TOXENV=py27
  - python: "3.5"
    env:
    - FLAG=false
      TOXENV=py35
  - python: "3.6"
    env:
    - FLAG=true
      TOXENV=py36
addons:
  apt:
    packages:
    - gcc
    - make
    - libssl-dev
    - python-pip
    - python-dev
    - build-essential
services:
- docker
install:
- travis_retry pip install tox
before_script:
- make docker-pull
script:
- make test VENV=$TOXENV
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$FLAG" == "true" ]]; then
    pip install -U bumpversion;
    git config --global user.email "builds@travis-ci.com";
    git config --global user.name "Travis CI";
    git pull --tags;
    bumpversion --tag --commit --message '[skip ci] Travis Build {$TRAVIS_BUILD_NUMBER}. Update version {current_version} --> {new_version}' patch modeldb/__init__.py;
    git push --follow-tags https://$GITHUB_TOKEN@github.com/engapa/modeldb-basic.git $TRAVIS_BRANCH;
    export RELEASE_TAGGED="true";
  fi

deploy:
- provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    condition: $RELEASE_TAGGED = true
- provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  on:
    branch: master
    condition: $RELEASE_TAGGED = true

notifications:
  email:
    recipients:
      - engapa@gmail.com
    on_success: never # default: change
    on_failure: always # default: always