language: python
dist: trusty
sudo: false
matrix:
  include:
  - python: "2.7"
    env:
    - FLAG=false
      TOXENV=py27
  - python: "3.5"
    env:
    - FLAG=false
      TOXENV=py35
  - python: "3.6"
    env:
    - FLAG=true
      TOXENV=py36
addons:
  apt:
    packages:
    - gcc
    - make
    - libssl-dev
    - python-pip
    - python-dev
    - build-essential
services:
- docker
install:
- travis_retry pip install tox
script:
- if [ -n "$TRAVIS_TAG" ]; then exit 0; fi
- TOXENV=$TOXENV make test
- |
  if [[ "$FLAG" == "true" ]]; then
    pip install -U bumpversion
    if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
      git config --global user.email "builds@travis-ci.com"
      git config --global user.name "Travis CI"
      git branch -a
      git checkout -b travis-master-$TRAVIS_BUILD_NUMBER origin/$TRAVIS_BRANCH
      git pull -t
      bumpversion --tag --commit \
        --message '[skip ci] Travis Build {$TRAVIS_BUILD_NUMBER}. Update version {current_version} --> {new_version}'\
        patch modeldb/__init__.py
      git checkout master
      git merge travis-master-$TRAVIS_BUILD_NUMBER
      git push --follow-tags https://$GITHUB_TOKEN@github.com/engapa/modeldb-basic.git $TRAVIS_BRANCH
      export RELEASE_TAGGED="true"
    else
      bumpversion patch modeldb/__init__.py;
    fi
  fi

before_deploy:
- |
  if [[ "$FLAG" == "true" ]]; then
    make build
  fi

deploy:
- provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^v.*$"
- provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^v.*$"

notifications:
  email:
    recipients:
      - engapa@gmail.com
    on_success: never # default: change
    on_failure: always # default: always